#!/bin/bash 

alias vrosrc='nvim ~/.rosrc'
alias srosrc='source ~/.rosrc'
alias vrosalias='nvim ~/.ros_aliases'
alias srosalias='source ~/.ros_aliases'

alias copter='source ~/copter_ws/devel/setup.bash --extend'
alias sdev='source devel/setup.zsh'
