#!/bin/sh

# If ROS is installed
if [ -d /opt/ros ]; then

    # # Add rospkg to python path
    if ! echo $PYTHONPATH | grep -q /usr/lib/python3/dist-packages; then
        export PYTHONPATH=$PYTHONPATH:/usr/lib/python3/dist-packages
    fi

    # # source correct ROS setup script
    if [ -n "$BASH" ]; then source /opt/ros/humble/setup.bash
    elif [ -n "$ZSH_NAME" ]; then source /opt/ros/humble/setup.zsh
    else
        source /opt/ros/humble/setup.sh
        echo_purple "[INFO] default ros setup.sh sourced"
    fi

    source /usr/share/colcon_cd/function/colcon_cd.sh
    export _colcon_cd_root=/opt/ros/humble/
    source /usr/share/colcon_argcomplete/hook/colcon-argcomplete.zsh
    complete -o nospace -o default -F _python_argcomplete "ros2"

    # # set ROS info
    export ROS_DOMAIN_ID=0

    # # print ROS info
    COFF="\033[0m"
    # echo_yellow "IP: $(hostname -I | cut -f1 -d' ')"
    # echo_yellow "IPs: $COFF$(myip)"
    echo_yellow "ROS_DOMAIN_ID: $COFF$ROS_DOMAIN_ID"

    # source my ros aliases
    if [ -f ~/.ros_aliases ]; then
        source ~/.ros_aliases
    fi

fi
