#!/bin/bash

ChangeVidSpeed() { ffmpeg -i "$1" -filter:v "setpts='$3'*PTS" "$2"; } # $1=input $2=output $3=frames to cut out (ex: 0.5)
cdl() { cd $1; ls ${2}; }
CropVid() { ffmpeg -i "$1" -ss "$3" -to "$4" -async 1 "$2"; } # $1=input $2=output $3=start_time (00:00:00) $4=end_time (00:01:30) for 1min 30sec

alias jdrive='sudo mount -t cifs //fs-caedm.et.byu.edu/mhask94 ~/J -o  username=mhask94,rw,uid=1002'
alias shutnow='sudo shutdown -P now'
alias vi='nvim'
alias nb='jupyter-notebook'
alias make='make -j8'
alias lscam='ls -ltrh /dev/video*'
alias vshalias='nvim ~/.sh_aliases'
alias scanip="nmap -sP 192.168.0.*"
alias untar='tar -xvzf'
alias keybind='gsettings set org.gnome.desktop.wm.keybindings'
alias qt='~/software/Qt/Tools/QtCreator/bin/qtcreator'
alias qtsh='~/software/Qt/Tools/QtCreator/bin/qtcreator.sh'
alias myip='hostname -I'
alias chterm='sudo update-alternatives --config x-terminal-emulator'
