#!/bin/sh

# functions
cdl() { cd $1; ls ${2}; }
ChangeVidSpeed() { # $1=input $2=output $3=frames to cut out (ex: 0.5)
    ffmpeg -i "$1" -filter:v "setpts='$3'*PTS" "$2"; } 
CropVid() { # $1=input $2=output $3=start_time (00:00:00) $4=end_time (00:01:30) for 1min 30sec
    ffmpeg -i "$1" -ss "$3" -to "$4" -async 1 "$2"; } 
lstty() { if (($#>0)); then for i in "$@"; do ls /dev/tty* | grep ${i}; done;
    else ls /dev/tty*; fi; }
ipscan() { ip_addr=$(hostname -I | cut -f1 -d' '); if [ -n "$ZSH_NAME" ]; then
    setopt shwordsplit; fi; saveIFS="$IFS"; IFS='.'; a=(${ip_addr}); 
    IFS="$saveIFS"; echo "${ip_addr%${a[-1]}}*"; nmap -sP "${ip_addr%${a[-1]}}*"
    }
code2pdf() { for var in "$@"; do vim "$var" -c ":hardcopy > temp.ps" -c ":q"; 
    ps2pdf temp.ps "${var%.*}".pdf; rm temp.ps; done; }
githubLatestRelease() { # $1=github_user/repo (ex: opencv/opencv)
    curl --silent "https://api.github.com/repos/$1/releases/latest" | 
        grep -Po '"tag_name": "\K.*?(?=")'
    }
githubLatestTag() { # $1=github_user/repo (ex: opencv/opencv)
    curl --silent "https://api.github.com/repos/$1/tags" | 
        grep -Po '"name": "\K.*?(?=")' | head -1
    }

# general aliases
alias jdrive='sudo mount -t cifs //fs-caedm.et.byu.edu/mhask94 ~/J -o username=mhask94,rw,uid=$(id -u)'
alias shutnow='systemctl poweroff'
alias vi='vim'
alias nb='jupyter-notebook'
alias make='make -j8'
alias lscam='ls -ltrh /dev/video*'
alias valias='vim ~/.sh_aliases'
alias salias='source ~/.sh_aliases'
alias scanip='nmap -sP 192.168.0.*'
alias untar='tar -xvzf'
alias keybind='gsettings set org.gnome.desktop.wm.keybindings'
alias myip='hostname -I'
alias me='echo_green $USER@$HOST'
alias chterm='sudo update-alternatives --config x-terminal-emulator'
alias cmaked='cmake -DCMAKE_BUILD_TYPE=Debug'
alias cmaker='cmake -DCMAKE_BUILD_TYPE=Release'

# location specific aliases
if [ -d ~/STM32CubeMX ]; then
    alias cubemx='~/STM32CubeMX/STM32CubeMX'; fi
if [ -d ~/Ac6 ]; then
    alias eclipse='~/Ac6/SystemWorkbench/eclipse'; fi
if [ -d ~/software/u-center_v19.05 ]; then
    alias ucenter='wine ~/software/u-center_v19.05/u-center.exe'; fi
if [ -d ~/software/demo5_b31a ]; then
    alias rtknavi='wine ~/software/demo5_b31a/rtknavi.exe'; fi
