#!/bin/sh

##################################  BASH  ######################################
if [ $BASH ]; then
  export GIT_PS1_SHOWDIRTYSTATE=1
  PS1='${debian_chroot:+($debian_chroot)}'
  PS1+='\[\033[00;92m\]\u@\h' # print username@hostname
  PS1+='\[\033[00m\]:'
  PS1+='\[\033[01;34m\]\w'            # print working directory
  PS1+='\[\033[00;33m\] $(__git_ps1)' # print git branch when in git repo
  PS1+='\n'                           # print new line before dollar sign
  PS1+='\[\033[00;92m\]\$'            # print dollar sign
  PS1+='\[\033[00m\] '                # reset color to white
fi

alias sbashrc='source ~/.bashrc'
alias vbashrc='vim ~/.bashrc'

##################################  ZSH  ######################################
alias szshrc='source ~/.zshrc'
alias vzshrc='vim ~/.zshrc'

##################################  BOTH  ######################################
alias stermrc='source ~/.termrc'
alias vtermrc='vi ~/.termrc'

# add ~/.local/bin to path if not already
if ! echo $PATH | grep -q /.local/bin; then
  export PATH=$PATH:$HOME/.local/bin
fi

# add ~/bin to path if not already
if ! echo $PATH | grep -q ${HOME}/bin; then
  export PATH=$PATH:$HOME/bin
fi

# add CUDA to path if not already
# if [ -d /usr/local/cuda/bin ]; then
#   if ! echo $PATH | grep -q /usr/local/cuda/bin; then
#     export PATH=$PATH:/usr/local/cuda/bin
#   fi
# fi

# source aliases
# if [ -f ~/.sh_aliases ]; then
source ~/.sh_aliases
# fi

if [ -d /opt/nvim-linux-x86_64 ]; then
  if ! echo $PATH | grep -q /opt/nvim; then
    export PATH="$PATH:/opt/nvim-linux-x86_64/bin"
  fi
fi

# source ros config
#if [ -f ~/.rosrc ]; then
#    . ~/.rosrc
#fi

# add gradle to path if not already
# if [ -d /opt/gradle ]; then
#   if ! echo $PATH | grep -q /opt/gradle; then
#     export PATH=$PATH:/opt/gradle/gradle-6.3/bin
#   fi
# fi

# add OpenCV to path if not already
# if [ -d /usr/local/opencv ]; then
#   if ! echo $PATH | grep -q /usr/local/opencv/bin; then
#     export PATH=$PATH:/usr/local/opencv/bin
#   fi
#   if ! echo $PYTHONPATH | grep -q opencv; then
#     export PYTHONPATH=$PYTHONPATH:/usr/local/opencv/lib/python3.8/dist-packages
#   fi
# fi

# add NUTTX arm-none-eabi-gcc to path if not already
# if [ -d /opt/gcc-arm-none-eabi-9-2020-q2-update ]; then
#   if ! echo $PATH | grep -q /opt/gcc-arm-none-eabi-9-2020-q2-update; then
#     export PATH=$PATH:/opt/gcc-arm-none-eabi-9-2020-q2-update/bin
#   fi
# fi

# Install Ruby Gems to ~/gems
# export GEM_HOME="$HOME/software/gems"
# export PATH="$PATH:$GEM_HOME/bin"

# Node.js (npm)
# export NVM_DIR="$HOME/.nvm"
#[ -s "$NVM_DIR/nvm.sh" ] && source "$NVM_DIR/nvm.sh"

# if ! echo $PATH | grep -q $NVM_BIN; then
#   export PATH=$PATH:$NVM_BIN
# fi

# if [ $BASH ]; then
#   [ -s "$NVM_DIR/bash_completion.sh" ] && source "$NVM_DIR/bash_completion.sh"
# fi

# Java
# export JAVA_HOME="/usr/lib/jvm/java-21-openjdk-amd64/bin/java"

#### DO THIS LAST!
# Activate venv last because it stores the state of PATH and restores previous
# state of PATH when you activate a different venv.

# Python virtual environments
if [ "$TERM_PROGRAM" != "vscode" ]; then
  if [ -d $HOME/.pyvenvs/default ]; then
    source $HOME/.pyvenvs/default/bin/activate
  fi
fi

