#!/bin/sh

##################################  BASH  ######################################
if [ $BASH ]; then
    export GIT_PS1_SHOWDIRTYSTATE=1
    PS1='${debian_chroot:+($debian_chroot)}';
    PS1+='\[\033[00;92m\]\u@\h';          # print username@hostname
    PS1+='\[\033[00m\]:';
    PS1+='\[\033[01;34m\]\w';             # print working directory
    PS1+='\[\033[00;33m\] $(__git_ps1)';  # print git branch when in git repo
    PS1+='\n';                            # print new line before dollar sign
    PS1+='\[\033[00;92m\]\$';             # print dollar sign
    PS1+='\[\033[00m\] ';                 # reset color to white
    
    alias sbashrc='source ~/.bashrc'
    alias vbashrc='vim ~/.bashrc'

##################################  ZSH  ######################################
elif [ $ZSH_NAME ]; then
    alias szshrc='source ~/.zshrc'
    alias vzshrc='vim ~/.zshrc'
fi

##################################  BOTH  ######################################
alias stermrc='source ~/.termrc'
alias vtermrc='vi ~/.termrc'

# Python virtual environments
if [ -f $HOME/.local/bin/virtualenvwrapper.sh ]; then
    export VIRTUALENVWRAPPER_PYTHON=/usr/bin/python3
    source $HOME/.local/bin/virtualenvwrapper.sh
fi

# add ~/.local/bin to path if not already
if ! echo $PATH | grep -q /.local/bin; then
    export PATH=$HOME/.local/bin:$PATH
fi

# add ~/bin to path if not already
if ! echo $PATH | grep -q ${HOME}/bin; then
    export PATH=$HOME/bin:$PATH
fi

# add CUDA to path if not already
if [ -d /usr/local/cuda/bin ]; then 
    if ! echo $PATH | grep -q /usr/local/cuda/bin; then
        export PATH=/usr/local/cuda/bin:$PATH
    fi
fi

# add OpenCV to path if not already
if [ -d /usr/local/opencv ]; then 
    if ! echo $PATH | grep -q /usr/local/opencv/bin; then
        export PATH=/usr/local/opencv/bin:$PATH
    fi
    export PYTHONPATH=/usr/local/opencv/lib/python3.6/dist-packages
fi

# source aliases
if [ -f ~/.sh_aliases ]; then
    . ~/.sh_aliases
fi

# source ros config
if [ -f ~/.rosrc ]; then
    . ~/.rosrc
fi
