[mgr]
ratio          = [1, 4, 3]
sort_by        = "natural"
sort_sensitive = false
sort_reverse   = false
sort_dir_first = true
show_hidden    = true
show_symlink   = true
linemode       = "size"

[preview]
tab_size        = 4
max_width       = 1024
max_height      = 1024
cache_dir       = ""
image_delay     = 30
